version: '3.7'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 1400:1400
    depends_on:
      - mongo
    networks:
      - app
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

networks:
  app:
    driver: bridge